CREATE TABLE CARTA (
    ID SERIAL,
    NOME VARCHAR(50) NOT NULL,
    TIPO VARCHAR(15) NOT NULL,
    ATRIBUTO VARCHAR(20) NOT NULL,
    DESCRICAO VARCHAR(100) NOT NULL,
    NIVEL INTEGER NOT NULL,
    ATK INTEGER NOT NULL,
    DEF INTEGER NOT NULL,
    CONSTRAINT PK_CARTA_ID PRIMARY KEY CARTA (ID)
);

CREATE TABLE USUARIO(
    ID SERIAL,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    SENHA VARCHAR(100) NOT NULL,
    ROLE VARCHAR(50) NOT NULL,
    CONSTRAINT PK_USUARIO_ID PRIMARY KEY USUARIO (ID)
)